Release 0.17.0-prerelease Improvements
microsoftgraph/entra-powershell pull request #1100
Opened 2024-09-19 13:28 UTC by SteveMutungi254

Release 0.17.0-prerelease Improvements

2024-09-21 22:13 UTC, alexandair requested changes

2024-09-21 22:13 UTC, alexandair commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUser.md
> +$usersInIndia = Get-EntraUser -Filter "Country eq 'India'"
Shouldn't this be `Get-EntraBetaUser`?

2024-09-22 17:39 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUser.md
> +$usersInIndia = Get-EntraUser -Filter "Country eq 'India'"
Great catch! Thank you.

2024-10-01 09:05 UTC, emmanuel-karanja approved these changes
LGTM

2024-10-02 08:00 UTC, KenitoInc commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraServicePrincipal.md
> +00001111-aaaa-2222-bbbb-3333cccc4444 SAML App                             True            33334444-dddd-5555-eeee-6666ffff7777 saml                              True                    AzureADMyOrg
```suggestion
00001111-aaaa-2222-bbbb-3333cccc4444 SAML App                             True            33334444-dddd-5555-eeee-6666ffff7777 saml                              True                    AzureADMyOrg   {admin@Contoso}
```

2024-10-02 08:36 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaServicePrincipal.md
> +Get-EntraBetaServicePrincipal -All | Where-Object {$_.appRoleAssignmentRequired -ne 'true'}
Synched offline. I am proposing we leave it as per the original proposal.

2024-10-02 08:42 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUser.md
> +Connect-Entra -Scopes 'AuditLog.Read.All','Directory.Read.All'
That is the right permission:

![alt text](image.png)

2024-10-02 08:42 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUser.md
> +cccccccc-2222-3333-4444-dddddddddddd  New User     NewUser@tenant.com        23/2102          Canada
Corrected. Thank you.

2024-10-02 10:04 UTC, KenitoInc approved these changes

2024-10-02 10:05 UTC, merged