Fix Find-EntraPermission to be consistent with Find-MgGraphPermission
microsoftgraph/entra-powershell pull request #1145
Opened 2024-10-08 08:48 UTC by emmanuel-karanja

-SearchString and -All belongs to different ParameterSets i.e. 'Search' and 'All' respectively as: 

![paramsets](https://github.com/user-attachments/assets/bfee59a9-3720-409c-b3b4-f1b20245a692)

2024-10-08 14:07 UTC, alexandair commented
Please, fix also the validate set for the -PermissionType parameter.
It should contain the following valid values:
Any, Application, and Delegated.

2024-10-09 09:37 UTC, KenitoInc requested changes

2024-10-09 09:37 UTC, KenitoInc commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Find-EntraPermission.md
> +Position: 0
```suggestion
Position: Named
```

2024-10-09 09:37 UTC, KenitoInc commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Find-EntraPermission.md
> + [-All]
The entire syntax section should be this

## SYNTAX

### Search
```
Find-EntraPermission
 [-SearchString] <String>
 [-ExactMatch]
 [-PermissionType <String>]
 [-Online]
 [<CommonParameters>]
```

### All
```
Find-EntraPermission
 [-PermissionType <String>]
 [-Online]
 [-All]
 [<CommonParameters>]
```

2024-10-16 07:19 UTC, KenitoInc approved these changes

2024-10-17 06:23 UTC, KenitoInc approved these changes

2024-10-17 06:23 UTC, merged