Enrich examples to boost example quality KPI
microsoftgraph/entra-powershell pull request #1158
Opened 2024-10-17 11:49 UTC by SteveMutungi254

Enrich examples to boost example quality KPI

2024-10-23 09:58 UTC, msewaweru requested changes
@SteveMutungi254 - left some comments for you. Thanks.

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaApplicationProxyApplication.md
> +The ApplicationId is a unique identifier for the application. You can find it using the Get-EntraBetaApplication command in PowerShell, or in the Microsoft Entra admin portal by navigating to Entra I
```suggestion
The ApplicationId is a unique identifier for the application. You can find it using the `Get-EntraBetaApplication` command in PowerShell, or in the Microsoft Entra admin portal by navigating to **Entra ID** > **Enterprise Applications** > **All Applications**, selecting your application, and viewing the **Properties** tab. Use the `ObjectId` value.
```

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraApplicationKey.md
>  $app = Get-EntraApplication -Filter "DisplayName eq '<application-display-name>'"
For conformity:
```suggestion
$application = Get-EntraApplication -Filter "DisplayName eq '<application-display-name>'"
```

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraApplicationKey.md
> +    ObjectId = $app.Id
Update the parameter descriptions after this example as well.
```suggestion
    ApplicationId = $application.Id
```

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraApplicationPassword.md
> +New-EntraApplicationPassword -ObjectId $application.Id -PasswordCredential $passwordCredential
```suggestion
New-EntraApplicationPassword -ApplicationId $application.Id -PasswordCredential $passwordCredential
```

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraApplicationServiceEndpoint.md
> +Get-EntraApplicationServiceEndpoint -ApplicationId $application.Id
Fails with an error: `A parameter cannot be found that matches parameter name 'ApplicationId'.`
```suggestion
Get-EntraApplicationServiceEndpoint -ObjectId $application.Id
```

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraApplicationServiceEndpoint.md
> +Get-EntraApplicationServiceEndpoint -ApplicationId $application.Id -All
Same error as above.

2024-10-23 09:58 UTC, msewaweru commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraApplicationServiceEndpoint.md
> +Get-EntraApplicationServiceEndpoint -ApplicationId $application.Id -Top 5
Same error as above.

2024-10-23 12:51 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraApplicationServiceEndpoint.md
> +Get-EntraApplicationServiceEndpoint -ApplicationId $application.Id -All
Great catch!

2024-10-23 12:57 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraApplicationServiceEndpoint.md
> +Get-EntraApplicationServiceEndpoint -ApplicationId $application.Id -Top 5
Great catch, @msewaweru!

2024-10-29 11:52 UTC, msewaweru approved these changes
Great job, @SteveMutungi254. Thanks.

2024-10-30 14:16 UTC, KenitoInc approved these changes

2024-10-30 14:36 UTC, merged