Modularization of Entra Powershell Module
microsoftgraph/entra-powershell pull request #1165
Opened 2024-10-21 08:00 UTC by emmanuel-karanja

The implementation to:

1. Split the Entra Module into Sub-modules.
2. Generate the new submodules in the bin directory.
3. Currently the typedefs appended to .psm1 file has been done as is i.e. we copy the entire string to the .psm1 file without splitting to get the relevant types,  it only adds them as they are.

2024-11-13 07:44 UTC, SamErde commented
I have a pretty tight week but will try to find time to check this out as soon as I can!

2024-11-13 07:55 UTC, SamErde commented on build/Split-Tests.ps1
> +# This function copies the docs using the moduleMapping.json into their submodule directories.
Looks like this description was copied and left from the Split-Docs function. Minor, but worth changing to speak regarding tests instead of docs.

2024-11-13 08:02 UTC, SamErde commented on build/Split-Tests.ps1
> +    $additionalTestFiles = @("General.Test.ps1", "Invalid.Tests.ps1", "Module.Tests.ps1", "Valid.Tests.ps1", "Entra.Tests.ps1")
I believe this should reference "General.Test***s***.ps1".

2024-11-13 08:28 UTC, SamErde commented on module/Entra/config/ModuleSettings.json
> +      "Microsoft.Graph",
Is the entire set of Microsoft.Graph submodules required? (I'm not yet clear about how this file is consumed and will keep reviewing.)

2024-11-13 08:38 UTC, SamErde commented on module/Entra/config/moduleMapping.json
Minor feedback:
- would be nice to have this list sorted by noun, verb or label, noun, verb
- would be nice to have consistent spacing between labels and values

2024-11-13 08:43 UTC, SamErde commented on module/Entra/customizations/Set-EntraUserExtension.ps1
Missing `begin {}` and `end {}` blocks.

Parameter options do not require ` = $true` when the added option is true (Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName, etc). It's a trivial string, but repeated use in a large module can add up.

2024-11-13 08:45 UTC, SamErde commented on module/EntraBeta/config/ModuleSettings.json
> +      "Microsoft.Graph.Beta",
Please consider removing this entry (which will install *all* Microsoft.Graph.Beta sub-modules) unless truly necessary.

2024-11-13 08:47 UTC, SamErde commented on module/EntraBeta/config/moduleMapping.json
Incomplete?

2024-11-13 08:54 UTC, SamErde commented on moduleVNext/Entra/config/ModuleMetadata.json
> +    "description": "Microsoft Entra PowerShell v1.0: Microsoft Entra PowerShell is a scenario-driven module that allows administrators to efficiently manage Entra ID resources, including users, group
Pleased to see it referred to as 'Microsoft Entra PowerShell.' Would be ideal for existing strings in the module's source and documentation to be changed from 'Microsoft.Graph.Entra' to 'Microsoft.Entra' and 'Microsoft.Graph.Entra.Beta' to 'Microsoft.Entra.Beta' (but I understand that change will take some time to implement).

2024-11-13 09:00 UTC, SamErde commented on moduleVNext/EntraBeta/config/dependencyMapping.json
> +    "Microsoft.Graph.Entra.Beta.Authentication":["Microsoft.Graph.Authentication"],
Microsoft.Graph.Beta.Authentication

2024-11-13 17:03 UTC, SamErde requested changes
Initial test results: I reviewed the build process, build scripts, and module configuration files. (25 files reviewed so far.) Was able to build the module, connect, and run a command, but some changes are necessary as noted in the comments.

2024-11-13 17:03 UTC, SamErde commented on build/VNext-Build.md
> +Alternatively, import the root module(that encompases and includes all the sub-modules and their help and dependencies) `Import-Module .\bin\Microsoft.Graph.Entra.psd1 -Force`
I proceeded with another fresh PowerShell session, imported the base module, and was able to connect and run `Get-EntraUser -Top 10`. 👍

2024-11-14 14:43 UTC, SamErde commented on src/EntraModuleBuilder.ps1
> +            return $subModules | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
`return` ends the pipeline, so there could be more flexibility in how this script is used if you remove the `return` statement from this line but leave the rest.

2024-11-14 14:52 UTC, SamErde commented
@emmanuel-karanja, @KenitoInc, @stevemutungi254, please let me know if the review and comments are helpful or if feedback would be best provided in a different manner. Thanks for the great work on this module!

2025-01-08 17:39 UTC, SamErde approved these changes

2025-01-13 15:08 UTC, SamErde approved these changes

2025-01-13 19:41 UTC, SamErde approved these changes

2025-01-28 11:53 UTC, SamErde commented on module/Entra/Microsoft.Entra/Authentication/Get-EntraContext.ps1
> +        $module = $ExecutionContext.SessionState.Module
I know you like clean formatting. It looks like VS Code forgot to trim this extra whitespace and blank line for you.

2025-02-03 08:44 UTC, KenitoInc approved these changes

2025-02-03 08:45 UTC, merged