New-EntraOauth2PermissionGrant GA and Beta
microsoftgraph/entra-powershell pull request #872
Opened 2024-06-27 12:13 UTC by v-akarke

…etaOauth2PermissionGrant

2024-07-01 08:46 UTC, alexandair requested changes

2024-07-01 08:46 UTC, alexandair commented on module/Entra/AdditionalFunctions/New-EntraOauth2PermissionGrant.ps1
> +    [CmdletBinding(DefaultParameterSetName = 'InvokeByDynamicParameters')]
The name of a parameter set should ideally tell what is specific for the set of parameters and why it is different than other sets. (The parameter set name is visible when the user runs `Show-Command <command>`).

`InvokeByDynamicParameters` doesn't do that.

2024-07-09 06:48 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +New-EntraBetaOauth2PermissionGrant -ClientId '00001111-aaaa-2222-bbbb-3333cccc4444' -ConsentType 'AllPrincipals' -ResourceId 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1' -Scope 'DelegatedPermissionGrant.Re
```suggestion
$params = @{
    ClientId = '00001111-aaaa-2222-bbbb-3333cccc4444'
    ConsentType = 'AllPrincipals'
    ResourceId = 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1'
    Scope = 'DelegatedPermissionGrant.ReadWrite.All'
    StartTime = Get-Date
    ExpiryTime = (Get-Date).AddYears(1)
}

New-EntraBetaOauth2PermissionGrant @params
```

2024-07-09 06:52 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +The `New-EntraBetaOauth2PermissionGrant` cmdlet Create a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource servic
```suggestion
The `New-EntraBetaOauth2PermissionGrant` cmdlet creates a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource service principal on behalf of a signed-in user, with access limited to the specified delegated permissions.
```

2024-07-09 06:55 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +New-EntraBetaOauth2PermissionGrant -ClientId '00001111-aaaa-2222-bbbb-3333cccc4444' -ConsentType 'Principal' -PrincipalId 'aaaaaaaa-bbbb-cccc-1111-222222222222' -ResourceId 'a0a0a0a0-bbbb-cccc-dddd-e
```suggestion
$params = @{
    ClientId = '00001111-aaaa-2222-bbbb-3333cccc4444'
    ConsentType = 'Principal'
    PrincipalId = 'aaaaaaaa-bbbb-cccc-1111-222222222222'
    ResourceId = 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1'
    Scope = 'DelegatedPermissionGrant.ReadWrite.All'
    StartTime = Get-Date
    ExpiryTime = (Get-Date).AddYears(1)
}

New-EntraBetaOauth2PermissionGrant @params
```

2024-07-09 06:56 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +Connect-Entra -Scopes 'Directory.ReadWrite.All'
```suggestion
Connect-Entra -Scopes 'DelegatedPermissionGrant.ReadWrite.All'
```

2024-07-09 06:56 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +Connect-Entra -Scopes 'Directory.ReadWrite.All'
```suggestion
Connect-Entra -Scopes 'DelegatedPermissionGrant.ReadWrite.All'
```

2024-07-09 07:00 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +Indicates if the client application is authorized to impersonate all users or only a specific user. "AllPrincipals" indicates authorization to impersonate all users, while "Principal" indicates autho
```suggestion
Indicates whether the client application is authorized to impersonate all users or only a specific user.

- `AllPrincipals`: Authorizes the application to impersonate all users.
- `Principal`: Authorizes the application to impersonate a specific user.

An administrator can grant consent on behalf of all users. In some cases, non-admin users are authorized to consent on behalf of themselves for certain delegated permissions. This parameter is required and supports the $filter query (eq only).
```

2024-07-09 07:02 UTC, SteveMutungi254 commented on module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
> +Create a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource service principal on behalf of a signed-in user, with
```suggestion
Create a delegated permission grant using an oAuth2PermissionGrant object. This grant allows a client service principal to access a resource service principal on behalf of a signed-in user, with access restricted to the specified delegated permissions.
```

2024-07-09 07:03 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +Create a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource service principal on behalf of a signed-in user, with
```suggestion
Create a delegated permission grant using an oAuth2PermissionGrant object. This grant allows a client service principal to access a resource service principal on behalf of a signed-in user, with access restricted to the specified delegated permissions.
```

2024-07-09 07:04 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +Indicates if the client application is authorized to impersonate all users or only a specific user. "AllPrincipals" indicates authorization to impersonate all users, while "Principal" indicates autho
```suggestion
Indicates whether the client application is authorized to impersonate all users or only a specific user.
- `AllPrincipals`: Authorizes the application to impersonate all users.
- `Principal`: Authorizes the application to impersonate a specific user.
An administrator can grant consent on behalf of all users. In some cases, non-admin users are authorized to consent on behalf of themselves for certain delegated permissions. This parameter is required and supports the $filter query (eq only).
```

2024-07-09 07:06 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +The `New-EntraOauth2PermissionGrant` cmdlet Create a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource service pr
```suggestion
The `New-EntraOauth2PermissionGrant` cmdlet creates a delegated permission grant using an oAuth2PermissionGrant object. This grant authorizes a client service principal to access a resource service principal on behalf of a signed-in user, with access limited to the specified delegated permissions.
```

2024-07-09 07:08 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +Connect-Entra -Scopes 'Directory.ReadWrite.All'
```suggestion
Connect-Entra -Scopes 'DelegatedPermissionGrant.ReadWrite.All'
```

2024-07-09 07:09 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +Connect-Entra -Scopes 'Directory.ReadWrite.All'
```suggestion
Connect-Entra -Scopes 'DelegatedPermissionGrant.ReadWrite.All'
```

2024-07-09 07:10 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +New-EntraOauth2PermissionGrant -ClientId '00001111-aaaa-2222-bbbb-3333cccc4444' -ConsentType 'Principal' -PrincipalId 'aaaaaaaa-bbbb-cccc-1111-222222222222' -ResourceId 'a0a0a0a0-bbbb-cccc-dddd-e1e1e
```suggestion
$params = @{
    ClientId = '00001111-aaaa-2222-bbbb-3333cccc4444'
    ConsentType = 'Principal'
    PrincipalId = 'aaaaaaaa-bbbb-cccc-1111-222222222222'
    ResourceId = 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1'
    Scope = 'DelegatedPermissionGrant.ReadWrite.All'
}

New-EntraOauth2PermissionGrant @params
```

2024-07-09 07:12 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
> +New-EntraOauth2PermissionGrant -ClientId '00001111-aaaa-2222-bbbb-3333cccc4444' -ConsentType 'AllPrincipals' -ResourceId 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1' -Scope 'DelegatedPermissionGrant.ReadWr
```suggestion
$params = @{
    ClientId = '00001111-aaaa-2222-bbbb-3333cccc4444'
    ConsentType = 'AllPrincipals'
    ResourceId = 'a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1'
    Scope = 'DelegatedPermissionGrant.ReadWrite.All'
}

New-EntraOauth2PermissionGrant @params
```

2024-07-09 07:13 UTC, SteveMutungi254 reviewed
Left some comments/suggestions.

2024-07-09 11:21 UTC, SteveMutungi254 approved these changes
LGTM.

2024-07-09 12:38 UTC, KenitoInc approved these changes

2024-07-09 15:49 UTC, merged