Bugfix - #902
microsoftgraph/entra-powershell pull request #923
Opened 2024-07-11 16:07 UTC by v-akarke

2024-07-11 18:20 UTC, SteveMutungi254 submitted a review, later dismissed
LGTM.

2024-07-12 07:40 UTC, KenitoInc requested changes

2024-07-12 07:40 UTC, KenitoInc commented on module/Entra/AdditionalFunctions/Get-EntraContext.ps1
>  function Get-EntraContext{
Add the MIT license. See this file
https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Add-EntraGroupOwner.ps1

2024-07-12 07:40 UTC, KenitoInc commented on module/EntraBeta/AdditionalFunctions/Get-EntraContext.ps1
> +function Get-EntraContext{
Add the MIT license. See this file
https://github.com/microsoftgraph/entra-powershell/blob/main/module/Entra/customizations/Add-EntraGroupOwner.ps1

2024-07-12 07:40 UTC, KenitoInc commented on module/Entra/AdditionalFunctions/Get-EntraContext.ps1
> +    PROCESS {
Remove whitespace

2024-07-12 08:36 UTC, KenitoInc approved these changes

2024-07-12 09:59 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Connect-Entra.md
> +For more information about Device Code flow, see <https://learn.microsoft.com/entra/identity-platform/v2-oauth2-device-code>.
```suggestion
For more information, see [Device Code flow](https://learn.microsoft.com/entra/identity-platform/v2-oauth2-device-code).
```

2024-07-12 10:01 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Connect-Entra.md
> +For more information on how to get or create access token, see <https://learn.microsoft.com/graph/auth-v2-user#3-request-an-access-token>.
```suggestion
For more information on how to get or create access token, see [Request an access token](https://learn.microsoft.com/graph/auth-v2-user#3-request-an-access-token).
```

2024-07-12 10:02 UTC, SteveMutungi254 commented on module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Connect-Entra.md
> +For more information on how to get or create CertificateThumbprint, see <https://learn.microsoft.com/powershell/entra-powershell/app-only-access-auth>.
```suggestion
For more information on how to get or create CertificateThumbprint, see [Authenticate with app-only access](https://learn.microsoft.com/powershell/entra-powershell/app-only-access-auth).
```

2024-07-12 10:59 UTC, KenitoInc approved these changes

2024-07-12 10:59 UTC, merged